choreizo_base:
    resource: "@ChoreizoBaseBundle/Resources/config/routing.yml"
    prefix:   /

choreizo_api:
    resource: "@ChoreizoApiBundle/Resources/config/routing.yml"
    prefix:   /api
    type: rest