choreizo_base_homepage:
    pattern:  /hello/{name}
    defaults: { _controller: ChoreizoBaseBundle:Default:index }


choreizo_paypal_callback:
    pattern: /paypal_login_callback
    defaults: { _controller: ChoreizoBaseBundle:Paypal:loginCallback }