parameters:
#    choreizo_base.example.class: Choreizo\Bundle\BaseBundle\Example

services:
#    choreizo_base.example:
#        class: %choreizo_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
