parameters:
    choreizo_base.paypal_client_id: 
    choreizo_base.paypal_client_secret: 
    choreizo_base.client_class: Guzzle\Http\Client
    choreizo_base.paypal_class: Choreizo\Bundle\BaseBundle\Service\Paypal

services:
    paypal:
        class: %choreizo_base.paypal_class%
        arguments: [%choreizo_base.paypal_client_id%, %choreizo_base.paypal_client_secret%]